package titans17576.season2022

//Arm positions in encoder ticks
val ARM_LOADING: Int = 0;
val ARM_TRANSITION_RISING = 475;
val ARM_LEVEL_3: Int = 718;
val ARM_LEVEL_3_MARK: Int = 728;
val ARM_LEVEL_2: Int = 975;
val ARM_TRANSITION_EXTENDED = 1100;
val ARM_LEVEL_1: Int = 1230;
val ARM_LEVEL_MAX: Int = 1000;

//Arm motor powers
val ARM_POWER_RESET: Double = -0.325;
val ARM_POWER_COMMAND = 0.7
val ARM_POWER_COMMAND_SLOW = 0.3
val ARM_POWER_CORRECT = 0.7

val INTAKE_IDLE_POWER = 0.0
val INTAKE_MAXPOW = 1.0
val INTAKE_INTAKE_POWER = INTAKE_MAXPOW
val INTAKE_EJECT_POWER = -INTAKE_MAXPOW
val INTAKE_EJECT_DURATION = 1500L
val INTAKE_DRAWER_OUT = 0.14
val INTAKE_DRAWER_IN = 0.03

//Bucket servo positions
val BUCKET_LOADING = 0.4
val BUCKET_TRANSITION_RISING = 0.13
val BUCKET_TRANSITION_LOWERING = 0.13
val BUCKET_DUMP = 0.80
val BUCKET_DUMP_MORE = 1.0
val BUCKET_BALANCED = 0.0
val BUCKET_TRANSITION_FALLING = 0.07

//Bucket clamp servo positions
val BUCKET_CLAMP_CLAMPING = 0.02
val BUCKET_CLAMP_RELEASE = 0.35

//TSE arm servo positions
val TSE_RAISED = 0.36
val TSE_DEPLOY = 0.5
val TSE_LOWERED = 0.85
val TSE_INSIDE = 0.05
val TSE_WIGGLE_DURATION = 275L
val TSE_WIGGLE_POSITION = TSE_INSIDE

//Carousel motor powers
val CAROUSEL_MAXPOW = 0.6
val CAROUSEL_MINPOW = 0.3
val CAROUSEL_MINPOW_ACTIVATION_LOWER = 0.075
val DISTANCE_SENSOR_ACTIVATION_UPPER = 8.5;
